// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfLYPd_qudNCmuKGbEu7GbGOTyuzAY-E4',
    appId: '1:248307239270:web:e6eec73f8e00437fd320a7',
    messagingSenderId: '248307239270',
    projectId: 'restauranteapp-42fd2',
    authDomain: 'restauranteapp-42fd2.firebaseapp.com',
    storageBucket: 'restauranteapp-42fd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb9Fd64aRDzLgtJS6yI_Eg9bWCQL5NnOA',
    appId: '1:248307239270:android:8e1fcda743a455f0d320a7',
    messagingSenderId: '248307239270',
    projectId: 'restauranteapp-42fd2',
    storageBucket: 'restauranteapp-42fd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWVlvt2cc3IDMX-tVufmCYNELbfHSks_s',
    appId: '1:248307239270:ios:6da4bc37dbbf1eaad320a7',
    messagingSenderId: '248307239270',
    projectId: 'restauranteapp-42fd2',
    storageBucket: 'restauranteapp-42fd2.firebasestorage.app',
    iosBundleId: 'com.example.dataAnalysisSa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWVlvt2cc3IDMX-tVufmCYNELbfHSks_s',
    appId: '1:248307239270:ios:6da4bc37dbbf1eaad320a7',
    messagingSenderId: '248307239270',
    projectId: 'restauranteapp-42fd2',
    storageBucket: 'restauranteapp-42fd2.firebasestorage.app',
    iosBundleId: 'com.example.dataAnalysisSa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfLYPd_qudNCmuKGbEu7GbGOTyuzAY-E4',
    appId: '1:248307239270:web:b727617fec390e9ed320a7',
    messagingSenderId: '248307239270',
    projectId: 'restauranteapp-42fd2',
    authDomain: 'restauranteapp-42fd2.firebaseapp.com',
    storageBucket: 'restauranteapp-42fd2.firebasestorage.app',
  );
}
